version: '3.3'

services:

  app:
    build: .
    image: celsotaliatelli/nginx-app:latest
    container_name: app-nginx
    ports:
      - 80:80
    volumes:
      - ./app/:/usr/share/nginx/bootstrap/html/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    environment:
      - NGINX_PORT=80
    networks:
      - app-network

  app-mysql:
        image: mysql:8.0.23
        ports:
            - 3306:3306
        volumes:
            - .docker/dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'my_db'
            MYSQL_USER: 'user_db'
            MYSQL_PASSWORD: 'secret'
            MYSQL_ROOT_PASSWORD: 'secret'
        networks: 
            - app-network
      
  php:
    build:
      context: ./phpFpm
    image: celsotaliatelli/php-app:latest
    container_name: php-server 
    volumes:
     - ./app/:/usr/share/nginx/bootstrap/html/app
    networks:
      - app-network
      
networks:
  app-network:
      driver: bridge